/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecordProductDialog.java
 *
 * Created on 2011-9-26, 13:07:54
 */
package pos;

import java.awt.event.KeyEvent;
import org.jdesktop.application.Action;

/**
 *
 * @author fangyuan01
 */
public class RecordProductDialog extends javax.swing.JDialog {

    /** Creates new form RecordProductDialog */
    public RecordProductDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codeTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        originalTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        singleTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        wholeTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buklTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        saleTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pos.POSApp.class).getContext().getResourceMap(RecordProductDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(778, 409));
        setName("Form"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pos.POSApp.class).getContext().getActionMap(RecordProductDialog.class, this);
        jButton2.setAction(actionMap.get("save")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("cancel")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton3.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        cancelBtn.setAction(actionMap.get("deleteProduct")); // NOI18N
        cancelBtn.setFont(resourceMap.getFont("cancelBtn.font")); // NOI18N
        cancelBtn.setText(resourceMap.getString("cancelBtn.text")); // NOI18N
        cancelBtn.setName("cancelBtn"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        codeTF.setText(resourceMap.getString("codeTF.text")); // NOI18N
        codeTF.setName("codeTF"); // NOI18N
        codeTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCode(evt);
            }
        });
        codeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monitorEnter(evt);
            }
        });

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        nameTF.setText(resourceMap.getString("nameTF.text")); // NOI18N
        nameTF.setName("nameTF"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        originalTF.setText(resourceMap.getString("originalTF.text")); // NOI18N
        originalTF.setName("originalTF"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        singleTF.setText(resourceMap.getString("singleTF.text")); // NOI18N
        singleTF.setName("singleTF"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        wholeTF.setText(resourceMap.getString("wholeTF.text")); // NOI18N
        wholeTF.setName("wholeTF"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        buklTF.setText(resourceMap.getString("buklTF.text")); // NOI18N
        buklTF.setName("buklTF"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        totalTF.setText(resourceMap.getString("totalTF.text")); // NOI18N
        totalTF.setName("totalTF"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        saleTF.setText(resourceMap.getString("saleTF.text")); // NOI18N
        saleTF.setName("saleTF"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(singleTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(originalTF, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(codeTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(totalTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(235, 235, 235)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saleTF, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(wholeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(nameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(buklTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(buklTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(singleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(wholeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(saleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    当焦点离开输入框时
private void inputCode(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCode
// TODO add your handling code here:
    setFieldsByCode(codeTF.getText());
}//GEN-LAST:event_inputCode

private void monitorEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monitorEnter
// TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        setFieldsByCode(codeTF.getText());
    }
}//GEN-LAST:event_monitorEnter

//当在输入框中输入Enter的时候
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordProductDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordProductDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordProductDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordProductDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RecordProductDialog dialog = new RecordProductDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setFieldsByCode(String code) {
        if(!POSUtils.isNull(code)){
             Product product = db.queryProductByCode(code);
             if(product != null) {
                 fillFields(product);
             } else {
                 resetFieldsExceptCode();
             }
        } else {
            resetFieldsExceptCode();
        }
    }
    
    public void fillFields(Product product) {
        this.nameTF.setText(product.getName());
        this.codeTF.setText(product.getCode());
        this.originalTF.setText(POSUtils.formatCash(product.getOriginalPrice()));
        this.buklTF.setText(POSUtils.formatCash(product.getDiscountPrice3()));
        this.singleTF.setText(POSUtils.formatCash(product.getDiscountPrice1()));
        this.wholeTF.setText(POSUtils.formatCash(product.getDiscountPrice2()));
        this.totalTF.setText(POSUtils.formatCash(product.getTotalNo()));
        this.saleTF.setText(POSUtils.formatCash(product.getSaleNo()));
    }
    
    
    public void resetFieldsExceptCode() {
        this.nameTF.setText("");
        this.originalTF.setText("");
        this.buklTF.setText("");
        this.singleTF.setText("");
        this.wholeTF.setText("");
        this.totalTF.setText("");
        this.saleTF.setText("");
    }
    
//    删除
    @Action
    public void deleteProduct() {
        String code = codeTF.getText();
        if(!POSUtils.isNull(code)) {
            if(db.hasProduct(code)) {
                 db.deleteProduct(code);
                 resetFieldsExceptCode();
                 this.codeTF.setText("");
                 POSUtils.showTips("产品删除成功！");
            } else {
                  POSUtils.showTips("商品已经不存在！");
            }        
        } else {
            POSUtils.showTips("请输入要删除产品的code！");
        }
    }

//    保存
    @Action
    public void save() {
        String name = this.nameTF.getText();
        String code = this.codeTF.getText();
        if(!POSUtils.isNull(code)&&!POSUtils.isNull(name)
                &&!POSUtils.isNull(this.originalTF.getText())
                &&!POSUtils.isNull(this.singleTF.getText())
                &&!POSUtils.isNull(this.wholeTF.getText())
                &&!POSUtils.isNull(this.buklTF.getText())
                &&!POSUtils.isNull(this.totalTF.getText())
                &&!POSUtils.isNull(this.saleTF.getText())){
            
            double originalPrice = Double.parseDouble(this.originalTF.getText());
            double discountPrice1 = Double.parseDouble(this.singleTF.getText());
            double discountPrice2 = Double.parseDouble(this.wholeTF.getText());
            double discountPrice3 = Double.parseDouble(this.buklTF.getText());
            double totalNo = Double.parseDouble(this.totalTF.getText());
            double saleNo = Double.parseDouble(this.saleTF.getText());

           if(db.hasProduct(code)) {
               db.updateProduct(code, name, originalPrice, discountPrice1, 
                       discountPrice2, discountPrice3, totalNo, saleNo);
               POSUtils.showTips("商品信息修改成功！");
               resetFieldsExceptCode();
               this.codeTF.setText("");
           } else {
               db.saveProduct(code, name, originalPrice, discountPrice1, 
                       discountPrice2, discountPrice3, totalNo, saleNo);
               POSUtils.showTips("商品信息保存成功！");
               resetFieldsExceptCode();
               this.codeTF.setText("");
           }
           
        } else {
          POSUtils.showTips("请输入产品的相关信息！");
        }
    }

//    取消
    @Action
    public void cancel() {
        this.dispose();
    }
    
    private DB db = new DB();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buklTF;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField codeTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField originalTF;
    private javax.swing.JTextField saleTF;
    private javax.swing.JTextField singleTF;
    private javax.swing.JTextField totalTF;
    private javax.swing.JTextField wholeTF;
    // End of variables declaration//GEN-END:variables
}
