/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateOrderItemDialog.java
 *
 * Created on 2011-9-25, 15:06:06
 */
package pos;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import org.jdesktop.application.Action;

/**
 *
 * @author fangyuan01
 */
public class UpdateOrderItemDialog extends javax.swing.JDialog {

    /** Creates new form UpdateOrderItemDialog */
    public UpdateOrderItemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public UpdateOrderItemDialog(java.awt.Frame parent, boolean modal,POSView parentView,
            int type, double no) {
        this(parent, modal);
        this.parentView = parentView;
        this.saleType = type;
        this.no = no;
   
//        初始化对话框的内容
        noTF.setText(POSUtils.formatCash(no));
        priceTF.setText(POSUtils.formatCash(0));
        saleTypeCB.setSelectedIndex(type-1);
        
//        价格是否显示
        if(POSUtils.isAdmin()) {
           showPrice();  
//           隐藏其它按钮
           this.authorityBtn.setVisible(false);
        } else {
           hidePrice();
        }
    }

    private void hidePrice() {
        priceLabel.setVisible(false);
        priceTF.setVisible(false);
    }
    
    private void showPrice() {
        priceLabel.setVisible(true);
        priceTF.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saleTypeCB = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        authorityBtn = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pos.POSApp.class).getContext().getResourceMap(UpdateOrderItemDialog.class);
        jPasswordField1.setText(resourceMap.getString("jPasswordField1.text")); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(673, 417));
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setForeground(resourceMap.getColor("jPanel1.foreground")); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(673, 417));
        jPanel1.setMinimumSize(new java.awt.Dimension(673, 417));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        noTF.setFont(resourceMap.getFont("noTF.font")); // NOI18N
        noTF.setText(resourceMap.getString("noTF.text")); // NOI18N
        noTF.setName("noTF"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        saleTypeCB.setFont(resourceMap.getFont("saleTypeCB.font")); // NOI18N
        saleTypeCB.setModel(saleTypeModel);
        saleTypeCB.setName("saleTypeCB"); // NOI18N
        saleTypeCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusSaleType(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pos.POSApp.class).getContext().getActionMap(UpdateOrderItemDialog.class, this);
        jButton1.setAction(actionMap.get("updateOrderItem")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        priceLabel.setFont(resourceMap.getFont("priceLabel.font")); // NOI18N
        priceLabel.setForeground(resourceMap.getColor("priceLabel.foreground")); // NOI18N
        priceLabel.setText(resourceMap.getString("priceLabel.text")); // NOI18N
        priceLabel.setName("priceLabel"); // NOI18N

        priceTF.setFont(resourceMap.getFont("priceTF.font")); // NOI18N
        priceTF.setText(resourceMap.getString("priceTF.text")); // NOI18N
        priceTF.setName("priceTF"); // NOI18N

        authorityBtn.setAction(actionMap.get("authorize")); // NOI18N
        authorityBtn.setFont(resourceMap.getFont("authorityBtn.font")); // NOI18N
        authorityBtn.setText(resourceMap.getString("authorityBtn.text")); // NOI18N
        authorityBtn.setName("authorityBtn"); // NOI18N

        errorMsg.setFont(resourceMap.getFont("errorMsg.font")); // NOI18N
        errorMsg.setForeground(resourceMap.getColor("errorMsg.foreground")); // NOI18N
        errorMsg.setText(resourceMap.getString("errorMsg.text")); // NOI18N
        errorMsg.setName("errorMsg"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(priceLabel)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(authorityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(saleTypeCB, 0, 276, Short.MAX_VALUE)
                    .addComponent(noTF, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(noTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(saleTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    当焦点到销售类型上时
private void focusSaleType(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusSaleType
// TODO add your handling code here:
    errorMsg.setText("");
}//GEN-LAST:event_focusSaleType

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UpdateOrderItemDialog dialog = new UpdateOrderItemDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

//    其它按钮
    @Action
    public void authorize() {
        if(!POSUtils.isAdmin()&&!this.hasAuthority) {
            JFrame mainFrame = POSApp.getApplication().getMainFrame();
            InputPasswordDialog passwordDialog = new InputPasswordDialog(mainFrame,true,this);
            passwordDialog.setLocationRelativeTo(mainFrame);
            passwordDialog.setAlwaysOnTop(true);
            POSApp.getApplication().show(passwordDialog);
        }
        if(this.hasAuthority) {
            showPrice();
        }
    }

//    确定按钮
    @Action
    public void updateOrderItem() {
        double price = Double.parseDouble(priceTF.getText());
        no = Double.parseDouble(noTF.getText());
        saleType= POSUtils.productSaleTypeStrToInt(saleTypeCB.getSelectedItem().toString());
        parentView.updateOrderItem(price, saleType, no);
        this.dispose();
     
    }
    
    private POSView parentView = null;
    private int saleType = Product.LOW_LEVEL;
    private double no = 0.0;
    
    private String[] saleTypes = {"零售","整售"};
    DefaultComboBoxModel saleTypeModel = new DefaultComboBoxModel(saleTypes);
    public boolean hasAuthority = false;
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorityBtn;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField noTF;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTF;
    private javax.swing.JComboBox saleTypeCB;
    // End of variables declaration//GEN-END:variables
}
